version: "3"

services:
  db:
    image: mysql:5.7.29
    container_name: mysql_mvc
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=test
    ports:
      - "3306:3306"
    volumes:
      - ../../Docker/MySql/mvc/conf:/etc/mysql/conf.d
      - ../../Docker/MySql/mvc/mysql:/var/lib/mysql

  app:
    build: .
    container_name: apache_php_mvc
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      PHP_IDE_CONFIG: "serverName=xdebug-docker"
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    links:
      - db
    depends_on:
      - db
    tty: true